version: '3.8'
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        container_name: php
        ports:
            - "${PORT_PHP}:${PORT_PHP}"
        volumes:
            - .:/var/www:cached
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - "${PORT_ENGINX}:${PORT_ENGINX}"
        volumes:
        - .:/var/www
        - ./.docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
        - ./.docker/nginx/nginx-config.sh:/docker-entrypoint.d/nginx-config.sh
        environment:
            NGINX_PORT: ${PORT_ENGINX}
        depends_on:
        - php


    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PORT_PHPMYADMIN}"
        links:
            - ${DB_HOST}
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${PMA_PORT}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 15G
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    db:
        image: mariadb:10.3
        restart: always
        ports:
            - ${PMA_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}






